version: "3.8"

services:

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: daisy
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: food
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: daisy
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: food
    depends_on:
      - db
volumes:
  postgres_data:

# To run the application, use the command:
# docker-compose up --build